"""add coluna nome na tabela usuario

Revision ID: 215511511ba1
Revises: ff4b8e0e95a2
Create Date: 2026-05-08 15:52:13.689919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215511511ba1'
down_revision: Union[str, Sequence[str], None] = 'ff4b8e0e95a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
